default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "your_username" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "your_password" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>

development:
  <<: *default
  database: sushi_delivery_development

test:
  <<: *default
  database: sushi_delivery_test

production:
  <<: *default
  database: sushi_delivery_production
  username: <%= ENV["SUSHI_DELIVERY_DB_USERNAME"] %>
  password: <%= ENV["SUSHI_DELIVERY_DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
