name: RSpec

on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main

jobs:
 rspec:
   runs-on: ubuntu-latest

   services:
     postgres:
       image: postgres:14.12
       env:
         POSTGRES_DB: study_fun_test
         POSTGRES_USER: ${{ secrets.DB_USERNAME }}
         POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
       options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=5
       ports:
         - 5432:5432

   steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Set environment variables
       run: |
         echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
         echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
         echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV

     - name: Set up Ruby
       uses: ruby/setup-ruby@v1
       with:
         ruby-version: '3.2.2'
         bundler-cache: true

     - name: Install dependencies
       run: bundle install

     - name: Set up the database
       run: |
         bundle exec rails db:create
         bundle exec rails db:schema:load

     - name: Run RSpec
       run: bundle exec rspec